GET http://localhost:9000/d
###

GET http://localhost:3004/movies/
###

GET http://localhost:3004/movies/2/
###

POST http://localhost:3004/movies/
Content-Type: application/json 

{
  "directorId": 6,
  "movieName": "Jurassic Park",
  "leadActor": "Jeff Goldblum"
}

###

PUT http://localhost:3004/movies/2/
Content-Type: application/json

{
  "directorId": 24,
  "movieName": "Thor",
  "leadActor": "Christopher Hemsworth"
}

###

DELETE http://localhost:3004/movies/2/
###

GET http://localhost:3004/directors/
###

GET http://localhost:3004/directors/1/movies/
###