GET http://localhost:9000/d
###

GET http://localhost:3004/movies/
###

GET http://localhost:9000/get/61deb698dde3d9e01a62a50d
###

POST http://localhost:3004/movies/
Content-Type: application/json 

{
  "directorId": 6,
  "movieName": "Jurassic Park",
  "leadActor": "Jeff Goldblum"
}

###

PUT http://localhost:9000/update/61de96ffab8cb6d6556d3fa4
Content-Type: application/json

{
  "ownerName": "RAM",
  "registrationNumber": "AP23-TD-1531",
  "vehicleColor": "BLUE",
  "slotNumber": 1
}

###

DELETE http://localhost:3004/movies/2/
###

GET http://localhost:3004/directors/
###

GET http://localhost:3004/directors/1/movies/
###