
GET http://localhost:9090/studentnames/
###


GET http://localhost:9090/studentsdata/
###

GET http://localhost:9090/getstudentsdata/
###

GET http://localhost:9090/students%20data%20age%20greaterthan/
###


GET http://localhost:9090/students%20names%20age%20greaterthan/
###

GET http://localhost:9090/studentnamesandagegreaterthan/
###

GET http://localhost:9090/studentnamesandagegreaterthaninsectionA/
###


GET http://localhost:9090/addField/
###

GET http://localhost:9090/diskuse/
###


GET http://localhost:9090/append/
###

GET http://localhost:9090/collation/
###

GET http://localhost:9090/count/
###

GET http://localhost:9090/exec/
###

GET http://localhost:9090/facet/
###

GET http://localhost:9090/group/
###

GET http://localhost:9090/limit/
###

GET http://localhost:9090/match/
###

GET http://localhost:9090/pipeline/
###

GET http://localhost:9090/project/
###

GET http://localhost:9090/projectavg/
###

GET http://localhost:9090/sample/
###


GET http://localhost:9090/search/
###

GET http://localhost:9090/skip/
###


GET http://localhost:9090/sort/
###

GET http://localhost:9090/sortbycount/
###

GET http://localhost:9090/unwind/
###


GET http://localhost:9090/unwindmulti/
###


GET http://localhost:9090/totalstudents/
###

GET http://localhost:9090/totalstudentseachclasswithmaxage/
###


GET http://localhost:9090/studentwithmaxage/
###

GET http://localhost:9090/distinctnames/
###

GET http://localhost:9090/lookup/
###

GET http://localhost:9090/andoperator/
###

GET http://localhost:9090/oroperator/
###


GET http://localhost:9090/notoperator/
###


GET http://localhost:9090/setequals/
###


GET http://localhost:9090/setintersection/
###


GET http://localhost:9090/setunion/
###

GET http://localhost:9090/setdifference/
###

GET http://localhost:9090/setissubset/
###

GET http://localhost:9090/anyelementtrue/
###

GET http://localhost:9090/allelementstrue/
###

GET http://localhost:9090/absolute/
###

GET http://localhost:9090/add/
###

GET http://localhost:9090/ceil/
###


GET http://localhost:9090/divide/
###

GET http://localhost:9090/floor/
###

GET http://localhost:9090/logarithm/
###

GET http://localhost:9090/log/
###

GET http://localhost:9090/mod/
###

GET http://localhost:9090/multiply/
###

GET http://localhost:9090/power/
###

GET http://localhost:9090/sqrt/
###


GET http://localhost:9090/concat/
###

GET http://localhost:9090/substr/
###

GET http://localhost:9090/lowerandupper/
###

GET http://localhost:9090/strcasecmp/
###


GET http://localhost:9090/redact/
###

GET http://localhost:9090/sample/
###

GET http://localhost:9090/getunwind/
###

GET http://localhost:9090/getgroup/
###

GET http://localhost:9090/out/
###

GET http://localhost:9090/arrayelemat/
###

GET http://localhost:9090/arrayconcat/
###

GET http://localhost:9090/arrayfilter/
###


GET http://localhost:9090/isarray/
###

GET http://localhost:9090/arraysize/
###

GET http://localhost:9090/arrayslice/
###

GET http://localhost:9090/dateformats/
###

GET http://localhost:9090/datetostring/
###

GET http://localhost:9090/sum/
###

GET http://localhost:9090/avg/
###

GET http://localhost:9090/roundingavg/
###


post http://localhost:9090/students/
Content-Type: application/json

[
    {
    "student_name": "siva",
    "class": 10,
    "section": "A",
    "subjects": ["English", "Telugu", "Maths"],
    "course_fee": 10000,
    "date_of_joining": "$2021-06-07-00:00:00Z",
    "age": 15,
    "weight": 40
},
{
    "student_name": "ashok",
    "class": 10,
    "section": "A",
    "subjects": ["English", "Telugu", "Maths", "Science"],
    "course_fee": 11000,
    "date_of_joining": "$2019-12-31-00:00:00Z",
    "age": 14,
    "weight": 38
},
{
    "student_name": "sowjanya",
    "class": 10,
    "section": "A",
    "subjects": ["English", "Telugu"],
    "course_fee": 12500,
    "date_of_joining": "$2020-07-21-00:00:00Z",
    "age": 13,
    "weight": 35
},
{
    "student_name": "Tanvi",
    "class": 10,
    "section": "A",
    "subjects": ["English", "Telugu", "Maths"],
    "course_fee": 10000,
    "date_of_joining": "$2021-06-07-00:00:00Z",
    "age": 12,
    "weight": 30
},
{
    "student_name": "kumar",
    "class": 10,
    "section": "B",
    "subjects": ["English", "Maths"],
    "course_fee": 9000,
    "date_of_joining": "$2017-11-31-00:00:00Z",
    "age": 15,
    "weight": 40
},
{
    "student_name": "ram",
    "class": 9,
    "section": "A",
    "subjects": ["English", "Maths"],
    "course_fee": 9000,
    "date_of_joining": "$2020-06-12-00:00:00Z",
    "age": 15,
    "weight": 40
},
{
    "student_name": "sivaram",
    "class": 9,
    "section": "B",
    "subjects": ["English", "Telugu"],
    "course_fee": 9000,
    "date_of_joining": "$2018-04-07-00:00:00Z",
    "age": 15,
    "weight": 40
},
{
    "student_name": "sivakumar",
    "class": 8,
    "section": "A",
    "subjects": ["English", "Maths", "Science"],
    "course_fee": 9000,
    "date_of_joining": "$2019-07-07-00:00:00Z",
    "age": 14,
    "weight": 33
},
{
    "student_name": "deva",
    "class": 7,
    "section": "A",
    "subjects": ["English", "Telugu"],
    "course_fee": 7000,
    "date_of_joining": "$2021-06-15-00:00:00Z",
    "age": 12,
    "weight": 28
},
{
    "student_name": "aditya",
    "class": 7,
    "section": "B",
    "subjects": ["English", "Maths"],
    "course_fee": 7000,
    "date_of_joining": "$2016-10-07-00:00:00Z",
    "age": 11,
    "weight": 27
},
{
    "student_name": "siva",
    "class": 7,
    "section": "B",
    "subjects": ["English", "Maths"],
    "course_fee": 7500,
    "date_of_joining": "$2021-05-07-00:00:00Z",
    "age": 12,
    "weight": 30
}
]
###

post http://localhost:9090/studentsmarks/
Content-Type: application/json

[
    {
    "name": "siva",
    "marks": 100,
    "age": 15
},
{
    "name": "ashok",
    "marks": 95,
    "age": 14
}, 
{
    "name": "sowjanya",
    "marks": 70,
    "age": 13
},
{
    "name": "Tanvi",
    "marks": 100,
    "age": 12
}
]

###


post http://localhost:9090/setoperators/
Content-Type: application/json


[
    { "A" : [ "red", "blue" ], "B" : [ "red", "blue" ] },
{ "A" : [ "red", "blue","blue" ], "B" : [ "blue", "red", "blue" ] },
{ "A" : [ "red", "blue" ], "B" : [ "red", "blue", "green" ] },
{ "A" : [ "red", "blue" ], "B" : [ "green", "red" ] },
{ "A" : [ "red", "blue" ], "B" : [ ] },
{ "A" : [ "red", "blue" ], "B" : [ [ "red" ], [ "blue" ] ] },
{ "A" : [ "red", "blue" ], "B" : [ [ "red", "blue" ] ] },
{ "A" : [ "red", "blue" ], "B" : [ "orange", "red", "blue"] },
{ "A" : [ ], "B" : [ ] },
{ "A" : [ ], "B" : [ "red" ] }
]
###