POST http://localhost:3004/postData
Content-Type: application/json

[
    {
        "student_name": "shiva",
        "class": "9",
        "section": "B",
        "subjects": ["maths","teligu","science","social","english","hindi"],
        "course_fee": "300000",
        "date_of_joining": "12-mach-2021",
        "age": "16",
        "weight": "55"
    },
    {
        "student_name": "harish",
        "class": "8",
        "section": "A",
        "subjects": ["maths","teligu","science","social","english","hindi"],
        "course_fee": "250000",
        "date_of_joining": "11-April-2021",
        "age": "15",
        "weight": "48"
    },
    {
        "student_name": "rahul",
        "class": "10",
        "section": "B",
        "subjects": ["maths","teligu","science","social","english","hindi"],
        "course_fee": "350000",
        "date_of_joining": "25-March-2021",
        "age": "18",
        "weight": "58"
    },
    {
        "student_name": "ajay",
        "class": "9",
        "section": "A",
        "subjects": ["maths","teligu","science","social","english","hindi"],
        "course_fee": "300000",
        "date_of_joining": "12-mach-2021",
        "age": "16",
        "weight": "55"
    },
    {
        "student_name": "mallesh",
        "class": "10",
        "section": "A",
        "subjects": ["maths","teligu","science","social","english","hindi"],
        "course_fee": "350000",
        "date_of_joining": "02-mach-2021",
        "age": "18",
        "weight": "55"
    },
    {
        "student_name": "abhi",
        "class": "8",
        "section": "A",
        "subjects": ["maths","teligu","science","social","english","hindi"],
        "course_fee": "250000",
        "date_of_joining": "1-April-2021",
        "age": "15",
        "weight": "45"
    },
    {
        "student_name": "krishna",
        "class": "10",
        "section": "A",
        "subjects": ["maths","teligu","science","social","english","hindi"],
        "course_fee": "380000",
        "date_of_joining": "19-May-2021",
        "age": "18",
        "weight": "65"
    },
    {
        "student_name": "sarath",
        "class": "9",
        "section": "B",
        "subjects": ["maths","teligu","science","social","english","hindi"],
        "course_fee": "300000",
        "date_of_joining": "12-mach-2021",
        "age": "16",
        "weight": "68"
    },
    {
        "student_name": "durga",
        "class": "8",
        "section": "B",
        "subjects": ["maths","teligu","science","social","english","hindi"],
        "course_fee": "330000",
        "date_of_joining": "12-march-2021",
        "age": "16",
        "weight": "52"
    },
    {
        "student_name": "sai",
        "class": "10",
        "section": "B",
        "subjects": ["maths","teligu","science","social","english","hindi"],
        "course_fee": "300000",
        "date_of_joining": "12-April-2021",
        "age": "16",
        "weight": "62"
    },
    {
        "student_name": "rajesh",
        "class": "10",
        "section": "A",
        "subjects": ["maths","teligu","science","social","english","hindi"],
        "course_fee": "390000",
        "date_of_joining": "12-Feb-2021",
        "age": "19",
        "weight": "62"
    },
    {
        "student_name": "raju",
        "class": "10",
        "section": "B",
        "subjects": ["maths","teligu","science","social","english","hindi"],
        "course_fee": "350000",
        "date_of_joining": "12-mach-2021",
        "age": "18",
        "weight": "56"
    },
    {
        "student_name": "venki",
        "class": "9",
        "section": "B",
        "subjects": ["maths","teligu","science","social","english","hindi"],
        "course_fee": "300000",
        "date_of_joining": "12-mach-2021",
        "age": "17",
        "weight": "53"
    }
]

###
GET http://localhost:3004/getData/

###
GET http://localhost:3004/getAdd/
###
GET http://localhost:3004/getAge/
###
GET http://localhost:3004/getNotAge/

###
GET http://localhost:3004/getStudentNameOrSection/

###
GET http://localhost:3004/getStudentNameSection/



//////////////////
###
POST http://localhost:3004/addSetEqualData/
Content-Type: application/json

[
    { "A" : [ "red", "blue" ], "B" : [ "red", "blue" ] },
{ "A" : [ "red", "blue" ], "B" : [ "blue", "red", "blue" ] },
{ "A" : [ "red", "blue" ], "B" : [ "red", "blue", "green" ] },
{ "A" : [ "red", "blue" ], "B" : [ "green", "red" ] },
{ "A" : [ "red", "blue" ], "B" : [ ] },
{ "A" : [ "red", "blue" ], "B" : [ [ "red" ], [ "blue" ] ] },
{ "A" : [ "red", "blue" ], "B" : [ [ "red", "blue" ] ] },
{ "A" : [ ], "B" : [ ] },
{ "A" : [ ], "B" : [ "red" ] }
]

###
GET http://localhost:3004/getSetEqualData

###
GET http://localhost:3004/getIntersectionData
###
GET http://localhost:3004/getUnionData

###
GET http://localhost:3004/getDifferenceData

###
GET http://localhost:3004/getIsSubsetData

###
GET http://localhost:3004/getAnyElementTrue

###
GET http://localhost:3004/getAllElementsTrue



///////////////////////////////////////////////////////////////

////   Arithmetic Aggregation Operators//////////////////////

////////////////////////////////////////////////////////////

###
GET http://localhost:3004/getAbsValues

###
GET http://localhost:3004/getAddedValues

###
GET http://localhost:3004/getCeilValues

###
GET http://localhost:3004/getExpValues

###
GET http://localhost:3004/getFloorValues
###
GET http://localhost:3004/getLnValues
