POST http://localhost:9000/createuser/
Content-Type: application/json

{
    "name": "ram",
    "roll": "teacher"
}
###

GET http://localhost:9000/getusers/

###

PUT http://localhost:9000/updateuser/
Content-Type: application/json

{   
    "_id": "61f26cc9d7e55b021b7485f3",
    "roll": "student"
}

###

POST http://localhost:9000/createclass/
Content-Type: application/json

{
    "class": "7",
    "description": "abcdef",
    "userId": "61f26cc9d7e55b021b7485f3"
}
###


GET http://localhost:9000/userclasses/61f25c838744232fc99d047d
###