POST http://localhost:9000/createuser/
Content-Type: application/json

{
    "name": "santhu",
    "roll": "teacher",
    "gender": "Female"
}
###

GET http://localhost:9000/getusers/

###

POST  http://localhost:9000/addfield/

###

PUT http://localhost:9000/updateuser/
Content-Type: application/json

{   
    "_id": "61f2d58a9782473b32d8fe0e",
    "roll": "student"
}

###

POST http://localhost:9000/createclass/
Content-Type: application/json

{
    "class": "1",
    "description": "abcdef",
    "userId": "61f2434305af74671c43ec1a"
}
###


POST http://localhost:9000/makeclass/
Content-Type: application/json

{
    "class": "3",
    "description": "abcdef",
    "userId": "61f2d58a9782473b32d8fe0e"
}
###


GET http://localhost:9000/userclasses/61f25c838744232fc99d047d
###

GET http://localhost:9000/getclasses
###