GET http://localhost:4000/getData/

###

GET http://localhost:4000/getStudentsMechanicalASection/

###

GET http://localhost:4000/getStudentsEitherMechOrComputers/

###

GET http://localhost:4000/getStudentsNotComputers/

###

POST http://localhost:4000/addData/
Content-Type: application/json

[
    {"A" : [ "red", "blue"], "B" : [ "red", "blue" ] },
    {"A" : [ "red", "blue","blue"], "B" : [ "blue", "red", "blue" ] },
    {"A" : [ "red", "blue" ], "B" : [ "red", "blue", "green" ] },
    {"A" : [ "red", "blue" ], "B" : [ "green", "red" ] },
    {"A" : [ "red", "blue" ], "B" : [ ] },
    {"A" : [ "red", "blue" ], "B" : [ [ "red" ], [ "blue" ] ] },
    {"A" : [ "red", "blue" ], "B" : [ [ "red", "blue" ] ] },
    {"A" : [ ], "B" : [ ] },
    {"A" : [ ], "B" : [ "red" ] }
]

###

GET http://localhost:4000/setEquales/
 
###

GET http://localhost:4000/commonData/

###

GET http://localhost:4000/setunionData/

###

GET http://localhost:4000/setDifferenceData/

###

GET http://localhost:4000/setIsSubsetData/

###

GET http://localhost:4000/absoluteValues/

###

GET http://localhost:4000/addMarks/

###

GET http://localhost:4000/ceilMarks/

###


GET http://localhost:4000/logarithm/

###

GET http://localhost:4000/reminder/

###

GET http://localhost:4000/multiple/

###

GET http://localhost:4000/power/

###

GET http://localhost:4000/concatNameAndCourse/

###

GET http://localhost:4000/substr/

###

GET http://localhost:4000/getSubjects/

###

GET http://localhost:4000/unwind/

###

GET http://localhost:4000/group/

###

GET http://localhost:4000/sample/

###

GET http://localhost:4000/outAgggregation/

###

GET http://localhost:4000/getFirstAndLastSubject/

###
GET http://localhost:4000/concatArrays/

###

GET http://localhost:4000/filter/

###

GET http://localhost:4000/isArray/

###

GET http://localhost:4000/isArraySize/

###

GET  http://localhost:4000/silceArray/

###


POST http://localhost:4000/addDate/
Content-Type: application/json

[
    { 
        "item" : "loptop", 
        "price" : "42000", 
        "quantity" : "2", 
        "date" : "$2014-01-01-00:00:00Z"
    },
    { 
        "item" : "TV", 
        "price" : "80000", 
        "quantity" : "1", 
        "date" : "$2013-02-29-00:00:00Z"
    },
    { 
        "item" : "lamp", 
        "price" : "500", 
        "quantity" : "4", 
        "date" : "$2013-02-25-00:00:00Z"
    },
    { 
        "item" : "Bike", 
        "price" : "89000", 
        "quantity" : "1", 
        "date" : "$2020-08-04-00:00:00Z"
    },
    { 
        "item" : "car", 
        "price" : "142000", 
        "quantity" : "1", 
        "date" : "$2021-04-01-00:00:00Z"
    },
    { 
        "item" : "TV", 
        "price" : "42000", 
        "quantity" : "1", 
        "date" : "$2019-02-21-00:00:00Z"
    }
]
###

GET http://localhost:4000/dateaggregation/

###

GET http://localhost:4000/dateStringFormate/

###

GET http://localhost:4000/totalPrice/

###

GET http://localhost:4000/avarage/

###

GET http://localhost:4000/firstGroupVaues/

###

GET http://localhost:4000/maximumPrice/

###

GET http://localhost:4000/pushItems/

###

GET http://localhost:4000/addTOSet/

###

GET http://localhost:4000/stdDevPop/